### ISSUE TITLE
Add support for the ATSAM21D family

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_Adalink#13]
It would be useful to add support to AdaLink for the ATSAM21D family, used on the Arduino Zeros.

**Comment by tdicola** [comment]
Just committed support for the ATSAM21D18 chip as a separate core.  It only supports that chip right now, but we can extend it to support the whole family as necessary.  Right now it only supports programming with a JLink, and doesn't have anything useful in the info command.  However it can wipe and write a bin file to the core (tested with an Arduino Zero).
