### ISSUE TITLE
Releases 

### ISSUE THREAD

**Issue by fabltd** [adafruit/Adafruit_Adalink#24]
Docs state:

Use a pre-built standalone binary distribution. See the releases tab for the current release for each platform (Windows, OSX).

Where are the pre-built binary's ? I cannot locate the releases tab.

**Comment by microbuilder** [comment]
On the home page under 'Releases' (bottom right-hand corner of the image below):

<img width="293" alt="screen shot 2017-08-03 at 13 52 45" src="https://user-images.githubusercontent.com/181073/28920671-17683e88-7853-11e7-815c-5f0c6eb16120.png">

Or just go here: https://github.com/adafruit/Adafruit_Adalink/releases
